### PR TITLE
Bench-Scale Demo Files

### PR DESCRIPTION
**Pull request by stephen-frank**
Merge bench-scale demo model and files into develop

### CODE REVIEW

**Comment by stephen-frank** [comment]
@avpreetothee There are some changes in BEEAM files associated with this pull request. I guess that means some components of the HPF library were tweaked to support this demo? Specifically;

- [HPF/DC/DC2DC_Converters/StepDown.mo](https://github.com/NREL/BEEAM/pull/5/files#diff-0b56698bef87843a65271b0ea861f74a3ff59c2e5cba55d1f68d16f87f5902ee)
- [HPF/Test/Test_timeSeriesInput.mo](https://github.com/NREL/BEEAM/pull/5/files#diff-ef1e62997e56faa746e26c884ae596bc0396d276a0f90ede6bc3803ee4cc9dd2)

I need to know whether the changes in this branch should be merged to `develop`, or whether the current versions in `develop` should take precedence over the ones in the `test-9` branch. You can see details on the *Files Changed* tab. Can you please advise?

**Comment by avpreetothee** [comment]
Hi Steve,
I didn't push any changes for the demo. What branch are you referring to that will be merged into develop?

**Comment by stephen-frank** [comment]
> What branch are you referring to that will be merged into develop?

The `test-9` branch (the one referenced by this pull request). I'm not sure why it is out of sync. If you look at the two files linked above, the `develop` version is on the left (shown in red, for blocks that will be replaced) and the version in the `test-9` branch is on the right (replacement blocks in green).

I wasn't expecting any changes to the models/files within the BEEAM library itself, which is why I'm asking you to double check whether those couple of files should be reverted to the versions in `develop`. On closer inspection, it seems most or maybe all the changes are cosmetic (e.g. block positions). It could have been someone inadvertently moving the blocks.

In any case, please just let me know whether the versions in `develop` take precedence over those in `test-9`.

**Comment by stephen-frank** [comment]
Also, take note I'm about to also create a pull request for the `flexlab-develop` branch, and I'll create a similar review request if there's anything weird I find there.

**Review by avpreetothee — APPROVED** [review]

**Review by avpreetothee — APPROVED** [review]

**Comment by stephen-frank** [comment]
I reverted the merge. The question above is still unresolved.

**Comment by stephen-frank** [comment]
Apvreet confirmed that the versions of the 2 files in `develop` are correct.

**Pull request merged**
